[package]
name = "propsheet-example"
version = "0.1.0"
edition = "2021"

[build-dependencies]
winres = "0.1"

[dependencies.windows]
version = "0.58.0"
features = [
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_UI_Controls",
    "Win32_UI_WindowsAndMessaging",
]